# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'clock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res
class moWidget(QtWidgets.QWidget):
    def __init__(self,parent=None):
        super(moWidget,self).__init__(parent)
        self.parent=parent
    def mousePressEvent(self, event):
        if event.button() == QtCore.Qt.LeftButton:
            self.dragPosition= event.globalPos() - self.parent.frameGeometry().topLeft()
            event.accept()

    def mouseMoveEvent(self,event):
        if event.buttons() == QtCore.Qt.LeftButton:
            self.parent.move(event.globalPos() - self.dragPosition)
            event.accept()
class Ui_MainWindow(object):
    def setTime(self):
        time=QtCore.QTime.currentTime()
        text=time.toString("HH:mm")
        self.label_2.setText(text)
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setGeometry(-5,-5,2000, 1080)

        MainWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        # MainWindow.setFixedSize(250, 180)

        # MainWindow.resize=False
        self.widget = moWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(1599,50, 240, 150))
        self.widget.setObjectName("widget")
        self.background = QtWidgets.QLabel(self.widget)
        self.background.setEnabled(True)
        self.background.setGeometry(QtCore.QRect(30, 30, 191, 90))
        self.background.setStyleSheet("background-image:url(:/img/background.PNG);\n"
"border-radius:10px;\n"
"background-position:center;\n"
"background-repeat:no-repeat;\n"
"border:5px solid white;")
        self.background.setText("")
        self.background.setObjectName("background")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 171, 71))
        font = QtGui.QFont()
        font.setFamily("OCR A Extended")
        font.setPointSize(33)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.grass = QtWidgets.QLabel(self.widget)
        self.grass.setGeometry(QtCore.QRect(20, 20, 271, 121))
        self.grass.setStyleSheet("background-image:url(:/img/grass.png);\n"
"background-position:center;\n"
"background-repeat:no-repeat;")
        self.grass.setText("")
        self.grass.setObjectName("grass")
        self.butterfly = QtWidgets.QLabel(self.widget)
        self.butterfly.setGeometry(QtCore.QRect(145, 0, 140, 80))
        self.butterfly.setText("")
        self.butterfly.setObjectName("butterfly")

        gifi=QtGui.QMovie(":/img/butterflies.gif")
        gifi.setScaledSize(QtCore.QSize().scaled(140,80,QtCore.Qt.KeepAspectRatio))
        self.butterfly.setMovie(gifi)
        gifi.start( )
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.background.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=15,xOffset=0,yOffset=0))
        self.label_2.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=5,xOffset=5,yOffset=5))

        timer=QtCore.QTimer(self.centralwidget)
        timer.timeout.connect(self.setTime)
        timer.start(100)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "10:10"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
